POST http://127.0.0.1:3000/auth/register
Content-Type: application/json 

{
    "name":"isma",
    "email":"casae@gmail.com",
    "password": "123401"
}

### login sin conexion a BDD
POST http://127.0.0.1:3000/auth/login
Content-Type: application/json 

{
    "name":"lyzon",
    "email":"willaim@jm.cep",
    "password": "1134578"
}


### users

GET http://127.0.0.1:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3Mjk5OTk5NjUsImV4cCI6MTczMDAwMDAyNX0.OUt2wUIu_QiP6fXHNBUXIMKwNMcLC1R3umKNcWOmoWA