### Listar productos
GET http://localhost:3000/producto

###Crear producto
POST http://localhost:3000/producto
Content-Type: application/json

{
    "nombre":"Impresora Laser",
    "precio":"500.95",
    "stock":12,
    "categoriaId":1
}

### Busqueda por nombre
GET http://localhost:3000/producto/back?sort=3